In [1]:
import numpy as np
import pandas as pd

patientdata = []
for filenum in range(1, 71):
    patientnum = 'Patient Number ' + str(filenum)
    if filenum < 10:
        with open("C:\\Users\\Ayman\\Documents\\machinelearning\\hw5\\diabetes-data\\Diabetes-Data\\data-0"+str(filenum), "r") as file:
            for line in file:
                fourth = str(line)
                date = fourth[0:fourth.index('\t')]
                fourth = fourth.replace(date, '')
                fourth = fourth.replace('\t', '', 1)
                time = fourth[0:fourth.index('\t')]
                fourth = fourth.replace(time, '')
                fourth = fourth.replace('\t', '', 1)
                third = fourth[0:fourth.index('\t')]
                patientdata.append(float(third))
    else:
        with open("C:\\Users\\Ayman\\Documents\\machinelearning\\hw5\\diabetes-data\\Diabetes-Data\\data-"+str(filenum), "r") as file:
            for line in file:
                fourth = str(line)
                date = fourth[0:fourth.index('\t')]
                fourth = fourth.replace(date, '')
                fourth = fourth.replace('\t', '', 1)
                time = fourth[0:fourth.index('\t')]
                fourth = fourth.replace(time, '')
                fourth = fourth.replace('\t', '', 1)
                third = fourth[0:fourth.index('\t')]
                patientdata.append(float(third))

df = pd.DataFrame(patientdata, columns=['col3'])#one hot encoding for the dataframe
onehotencoded = pd.get_dummies(df['col3'], prefix='col3')
datahot = pd.concat([df, onehotencoded], axis=1)

#df_encoded.to_csv("C:\\Users\\Ayman\\Documents\\machinelearning\\hw4\\test_encoded.csv", index=False)
#print(df_encoded)

In [2]:
datahot = datahot.astype(int)#convering the booleans to int for 0 and 1
print(datahot.values)

[[58  0  0 ...  0  0  0]
 [33  0  0 ...  0  0  0]
 [34  0  0 ...  0  0  0]
 ...
 [34  0  0 ...  0  0  0]
 [34  0  0 ...  0  0  0]
 [34  0  0 ...  0  0  0]]


In [3]:
n = 5
def generatengrams(data, n):
    ngrams_list = [tuple(data[i:i+n]) for i in range(len(data)-n+1)]
    return ngrams_list

ngrams = generatengrams(patientdata, n)#generating ngrams and placing those ngrams into the dataframe

ngramsdf = pd.DataFrame(ngrams, columns=[f'Ngram_{i+1}' for i in range(n)])

print(ngramsdf)

       Ngram_1  Ngram_2  Ngram_3  Ngram_4  Ngram_5
0         58.0     33.0     34.0     62.0     33.0
1         33.0     34.0     62.0     33.0     48.0
2         34.0     62.0     33.0     48.0     58.0
3         62.0     33.0     48.0     58.0     33.0
4         33.0     48.0     58.0     33.0     34.0
...        ...      ...      ...      ...      ...
29321     33.0     34.0     48.0     58.0     33.0
29322     34.0     48.0     58.0     33.0     34.0
29323     48.0     58.0     33.0     34.0     34.0
29324     58.0     33.0     34.0     34.0     34.0
29325     33.0     34.0     34.0     34.0     34.0

[29326 rows x 5 columns]


In [6]:
def hashing(patientdata, n):
    hashed = np.zeros(n)
    for x in patientdata:
        i = hash(str(x)) % n
        hashed[i] += 1
    return hashed
hasheddata = hashing(patientdata, 100)
print(hasheddata)

[0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
 0.000e+00 0.000e+00 0.000e+00 2.000e+01 0.000e+00 0.000e+00 0.000e+00
 3.310e+02 1.053e+03 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
 0.000e+00 0.000e+00 3.400e+01 0.000e+00 0.000e+00 3.260e+02 0.000e+00
 3.160e+03 3.300e+01 9.040e+02 1.883e+03 6.600e+01 0.000e+00 0.000e+00
 0.000e+00 9.518e+03 0.000e+00 0.000e+00 0.000e+00 9.900e+02 0.000e+00
 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 6.800e+01
 2.200e+02 0.000e+00 1.190e+02 0.000e+00 0.000e+00 0.000e+00 0.000e+00
 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
 1.540e+02 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 9.400e+01
 2.771e+03 0.000e+00 0.000e+00 9.800e+01 0.000e+00 0.000e+00 3.518e+03
 3.969e+03 1.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
 0.000

In [24]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X = datahot.drop(['col3'], axis=1)
y = datahot['col3']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)#splitting everything

In [25]:
def svd(X, n_components):
    # Initialize random unitary matrices
    U = np.random.rand(X.shape[0], n_components)
    V = np.random.rand(X.shape[1], n_components)

    for ii in range(100):  # Adjust the number of iterations as needed
        U, temp = np.linalg.qr(X @ V)
        V, temp = np.linalg.qr(X.T @ U)

    sigma = U.T @ X @ V
    return U, sigma, V.T

# Assuming X is your data matrix
u, Sigma, vt = svd(X.to_numpy(), 7)
print(vt.shape)
print(Sigma.shape)
print(u.shape)


(7, 24)
(7, 7)
(29330, 7)


In [29]:
import numpy as np

def knn(X_train, y_train, X_test, k, n_components):
    u, sigma, vt = svd(X_train, n_components)
    top = vt[:n_components, :]
    xtests = X_test @ top.T
    predictions = []
    for point in xtests:
        distances = np.linalg.norm(X_train @ top.T - point, axis=1)
        neighbors_indices = np.argsort(distances)[:k]
        neighbors_labels = y_train.iloc[neighbors_indices]
        predicted_label = neighbors_labels.value_counts().idxmax()
        predictions.append(predicted_label)

    return predictions

pred = knn(X_train.to_numpy(), y_train, X_test.to_numpy(), 3, 7)
acc = accuracy_score(y_test, pred)
print(pred)
print(acc)


[34, 33, 34, 33, 34, 34, 68, 60, 34, 65, 33, 33, 60, 57, 33, 70, 35, 64, 58, 60, 33, 33, 33, 58, 33, 34, 33, 60, 62, 34, 60, 33, 60, 34, 33, 48, 33, 35, 58, 34, 35, 63, 33, 33, 33, 33, 34, 64, 62, 33, 48, 33, 33, 33, 62, 48, 33, 58, 33, 33, 62, 60, 57, 58, 62, 62, 48, 60, 62, 33, 58, 64, 33, 58, 48, 33, 58, 33, 57, 48, 58, 33, 58, 33, 60, 62, 33, 58, 48, 48, 60, 62, 60, 57, 60, 67, 35, 33, 35, 34, 33, 66, 60, 34, 35, 62, 33, 62, 57, 33, 60, 33, 35, 34, 34, 58, 58, 58, 60, 58, 48, 48, 48, 48, 33, 34, 60, 58, 62, 33, 34, 34, 33, 58, 62, 33, 35, 34, 62, 33, 64, 33, 64, 62, 34, 48, 62, 33, 33, 33, 33, 64, 48, 70, 33, 48, 67, 48, 33, 60, 62, 65, 34, 33, 62, 62, 33, 58, 33, 34, 33, 62, 33, 33, 58, 35, 33, 58, 62, 60, 58, 58, 35, 62, 34, 34, 33, 33, 57, 58, 33, 48, 60, 60, 58, 33, 34, 34, 58, 33, 34, 62, 33, 62, 33, 60, 58, 48, 33, 62, 58, 60, 58, 58, 58, 34, 33, 33, 34, 48, 58, 34, 33, 62, 34, 48, 60, 62, 58, 62, 33, 66, 48, 34, 33, 64, 57, 58, 58, 33, 60, 34, 60, 48, 62, 34, 34, 33, 33, 33,

In [28]:
import numpy as np

X_train_proj = 0
X_test_proj = 0

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def logisticregression(X_train, y_train, X_test, learnrate, i, n):
    u, sigma, vt = svd(X_train, n)
    top = vt[:n, :]

    X_train_proj = X_train @ top.T
    X_test_proj = X_test @ top.T


    weights = np.zeros(n)
    bias = 0


    for ii in range(i):
        probabilities = sigmoid(X_train_proj @ weights + bias)
        gradient = X_train_proj.T @ (probabilities - y_train) / len(y_train)
        weights -= learnrate * gradient
        bias -= learnrate * np.sum(probabilities - y_train) / len(y_train)
    pred = sigmoid(X_test_proj @ weights + bias) 

    return pred

pred = logisticregression(X_train.to_numpy(), y_train, X_test.to_numpy(), .01, 1000,5)
accuracy = accuracy_score(y_test, pred)
print("Accuracy:", accuracy)
print(pred)


Accuracy: 0.0
[1. 1. 1. ... 1. 1. 1.]


In [27]:
def fit(X, y, n):
    U, Sigma, Vt = svd(X, n)
    
    classes, counts = np.unique(y, return_counts=True)
    class_prob = counts / len(y)
    
    feature_prob = []
    
    for c in classes:
        label_is_c = (y == c)
        class_count = np.sum(label_is_c)
        X_class = X[label_is_c].to_numpy() @ Vt.T  
        currfeat = (X_class + 1) / (class_count + np.abs(X_class).shape[1])
        currfeat = currfeat.flatten()
        
        feature_prob.append(currfeat)

    return class_prob, feature_prob, classes, Vt


def naivebayes(X, class_prob_final, feature_prob_final, classes, Vt):
    predictions = []
    X_test_svd = X @ Vt.T
    
    for xx in X_test_svd:
        class_prob_x = np.log(class_prob_final)
        
        for i, c in enumerate(classes):
            currfeat = np.log(feature_prob_final[i])
            currpred = np.sum(currfeat * xx)
            class_prob_x[i] += currpred.item() if isinstance(currpred, np.ndarray) else currpred
        
        prediction = classes[np.argmax(class_prob_x)]
        predictions.append(prediction)
    
    return np.array(predictions)
class_prob_final, feature_prob_final, classes, Vt = fit(X_train, y_train, 7)

pred = naivebayes(X_test, class_prob_final, feature_prob_final, classes, Vt)


print(pred)

[33 59 59 59 59 59 59]
