In [3]:
import numpy as np
import pandas as pd

patientdata = []
for filenum in range(1, 71):
    patientnum = 'Patient Number ' + str(filenum)
    if filenum < 10:
        with open("C:\\Users\\Ayman\\Documents\\machinelearning\\hw5\\diabetes-data\\Diabetes-Data\\data-0"+str(filenum), "r") as file:
            for line in file:
                fourth = str(line)
                date = fourth[0:fourth.index('\t')]
                fourth = fourth.replace(date, '')
                fourth = fourth.replace('\t', '', 1)
                time = fourth[0:fourth.index('\t')]
                fourth = fourth.replace(time, '')
                fourth = fourth.replace('\t', '', 1)
                third = fourth[0:fourth.index('\t')]
                patientdata.append(float(third))
    else:
        with open("C:\\Users\\Ayman\\Documents\\machinelearning\\hw5\\diabetes-data\\Diabetes-Data\\data-"+str(filenum), "r") as file:
            for line in file:
                fourth = str(line)
                date = fourth[0:fourth.index('\t')]
                fourth = fourth.replace(date, '')
                fourth = fourth.replace('\t', '', 1)
                time = fourth[0:fourth.index('\t')]
                fourth = fourth.replace(time, '')
                fourth = fourth.replace('\t', '', 1)
                third = fourth[0:fourth.index('\t')]
                patientdata.append(float(third))

df = pd.DataFrame(patientdata, columns=['col3'])#one hot encoding for the dataframe
onehotencoded = pd.get_dummies(df['col3'], prefix='col3')
datahot = pd.concat([df, onehotencoded], axis=1)

#df_encoded.to_csv("C:\\Users\\Ayman\\Documents\\machinelearning\\hw4\\test_encoded.csv", index=False)
#print(df_encoded)

In [4]:
datahot = datahot.astype(int)#convering the booleans to int for 0 and 1
print(datahot.values)

[[58  0  0 ...  0  0  0]
 [33  0  0 ...  0  0  0]
 [34  0  0 ...  0  0  0]
 ...
 [34  0  0 ...  0  0  0]
 [34  0  0 ...  0  0  0]
 [34  0  0 ...  0  0  0]]


In [5]:
n = 5
def generatengrams(data, n):
    ngrams_list = [tuple(data[i:i+n]) for i in range(len(data)-n+1)]
    return ngrams_list

ngrams = generatengrams(patientdata, n)#generating ngrams and placing those ngrams into the dataframe

ngramsdf = pd.DataFrame(ngrams, columns=[f'Ngram_{i+1}' for i in range(n)])

print(ngramsdf)

       Ngram_1  Ngram_2  Ngram_3  Ngram_4  Ngram_5
0         58.0     33.0     34.0     62.0     33.0
1         33.0     34.0     62.0     33.0     48.0
2         34.0     62.0     33.0     48.0     58.0
3         62.0     33.0     48.0     58.0     33.0
4         33.0     48.0     58.0     33.0     34.0
...        ...      ...      ...      ...      ...
29321     33.0     34.0     48.0     58.0     33.0
29322     34.0     48.0     58.0     33.0     34.0
29323     48.0     58.0     33.0     34.0     34.0
29324     58.0     33.0     34.0     34.0     34.0
29325     33.0     34.0     34.0     34.0     34.0

[29326 rows x 5 columns]


In [6]:
def hashing(patientdata, n):
    hashed = np.zeros(n)
    for x in patientdata:
        i = hash(str(x)) % n
        hashed[i] += 1
    return hashed
hasheddata = hashing(patientdata, 100)
print(hasheddata)

[0.000e+00 0.000e+00 0.000e+00 0.000e+00 1.883e+03 0.000e+00 0.000e+00
 0.000e+00 2.390e+02 0.000e+00 0.000e+00 9.518e+03 0.000e+00 0.000e+00
 0.000e+00 0.000e+00 2.771e+03 1.000e+00 0.000e+00 0.000e+00 0.000e+00
 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
 3.830e+03 0.000e+00 0.000e+00 0.000e+00 6.600e+01 0.000e+00 0.000e+00
 9.400e+01 3.310e+02 0.000e+00 1.540e+02 0.000e+00 0.000e+00 0.000e+00
 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
 0.000e+00 0.000e+00 0.000e+00 1.000e+00 1.190e+02 0.000e+00 9.900e+02
 0.000e+00 3.657e+03 1.053e+03 0.000e+00 0.000e+00 0.000e+00 0.000e+00
 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
 0.000e+00 9.800e+01 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
 6.700e+01 0.000e+00 0.000e+00 3.160e+03 0.000e+00 0.000e+00 0.000e+00
 0.000e+00 0.000e+00 0.000e+00 6.800e+01 0.000e+00 9.040e+02 3.260e+02
 0.000

In [1]:

x = datahot.drop(columns=['col3']).values 
y = datahot['col3'].values  # Labels


def decision(w, b, x):
    return np.dot(x, w) + b

def hingeloss(w, b, x, y):
    margin = 1 - y * decision(w, b, x)
    return np.maximum(0, margin)

def objective(w, b, C, x, y):
    return 0.5 * np.dot(w, w) + C * np.mean(hingeloss(w, b, x, y))


def gradients(w, b, C, x, y):
    margin = 1 - y * decision(w, b, x)
    indicator = (margin > 0).astype(int)
    dw = w - C * np.dot(x.T, y * indicator) / len(y)
    db = -C * np.sum(y * indicator) / len(y)
    return dw, db



learning_rate = 0.01
num_epochs = 1000


for epoch in range(num_epochs):
    dw, db = gradients(np.zeros(x.shape[1]), 0, 1.0, x, y)

    w -= learning_rate * dw
    b -= learning_rate * db
    

    loss = objective(w, b, C, x, y)
    print(f'Epoch {epoch}: Loss = {loss}')








NameError: name 'datahot' is not defined

In [26]:
import numpy as np

def decision(w, b, x):
    return np.dot(x, w) + b

def hingeloss(w, b, x, y):
    margin = 1 - y * decision(w, b, x)
    return np.maximum(0, margin)

def objective(w, b, C, x, y):
    return 0.5 * np.dot(w, w) + C * np.mean(hingeloss(w, b, x, y))

def gradients(w, b, C, x, y):
    margin = 1 - y * decision(w, b, x)
    indicator = (margin > 0).astype(int)
    dw = w - C * np.dot(x.T, y * indicator) / len(y)
    db = -C * np.sum(y * indicator) / len(y)
    return dw, db

def trainsvc(x, y, C, learning_rate, num_epochs):
    w = np.zeros(x.shape[1]) 
    b = 0 
    for epoch in range(num_epochs):

        dw, db = gradients(w, b, C, x, y)
        w -= learning_rate * dw
        b -= learning_rate * db

        loss = objective(w, b, C, x, y)
        print(f'Epoch {epoch}: Loss = {loss}')
    print("Training completed!")
    return w, b



wsvc, bsvc = trainsvc(x, y, 1.0, .01, 1000)






Epoch 0: Loss = 0.015123657441642761
Epoch 1: Loss = 0.01484508670287729
Epoch 2: Loss = 0.01457205952181325
Epoch 3: Loss = 0.014304465581652383
Epoch 4: Loss = 0.01404219676090072
Epoch 5: Loss = 0.013785147089682015
Epoch 6: Loss = 0.013533212706920561
Epoch 7: Loss = 0.013286291818376062
Epoch 8: Loss = 0.013044284655513596
Epoch 9: Loss = 0.012807093435192096
Epoch 10: Loss = 0.012574622320154992
Epoch 11: Loss = 0.012346777380307128
Epoch 12: Loss = 0.012123466554762232
Epoch 13: Loss = 0.011904599614645682
Epoch 14: Loss = 0.011690088126637452
Epoch 15: Loss = 0.011479845417240587
Epoch 16: Loss = 0.011273786537760717
Epoch 17: Loss = 0.011071828229982495
Epoch 18: Loss = 0.010873888892529065
Epoch 19: Loss = 0.010679888547890953
Epoch 20: Loss = 0.010489748810111143
Epoch 21: Loss = 0.01030339285311315
Epoch 22: Loss = 0.010120745379659417
Epoch 23: Loss = 0.009941732590927411
Epoch 24: Loss = 0.009766282156691177
Epoch 25: Loss = 0.00959432318609624
Epoch 26: Loss = 0.00942578

Epoch 234: Loss = 0.0012519962637286349
Epoch 235: Loss = 0.0012494715824036536
Epoch 236: Loss = 0.0012469971422370395
Epoch 237: Loss = 0.0012445719434297409
Epoch 238: Loss = 0.0012421950060787076
Epoch 239: Loss = 0.00123986536978096
Epoch 240: Loss = 0.0012375820932455375
Epoch 241: Loss = 0.0012353442539131698
Epoch 242: Loss = 0.0012331509475835161
Epoch 243: Loss = 0.0012310012880498227
Epoch 244: Loss = 0.00122889440674085
Epoch 245: Loss = 0.0012268294523699254
Epoch 246: Loss = 0.0012248055905909826
Epoch 247: Loss = 0.0012228220036614404
Epoch 248: Loss = 0.0012208778901117963
Epoch 249: Loss = 0.0012189724644217901
Epoch 250: Loss = 0.001217104956703015
Epoch 251: Loss = 0.0012152746123878437
Epoch 252: Loss = 0.0012134806919245442
Epoch 253: Loss = 0.0012117224704784643
Epoch 254: Loss = 0.0012099992376391614
Epoch 255: Loss = 0.0012083102971333607
Epoch 256: Loss = 0.0012066549665436252
Epoch 257: Loss = 0.0012050325770326257
Epoch 258: Loss = 0.001203442473072895
Epoch 

Epoch 492: Loss = 0.0011258376193332485
Epoch 493: Loss = 0.0011258234950317354
Epoch 494: Loss = 0.0011258096518038225
Epoch 495: Loss = 0.001125796084056145
Epoch 496: Loss = 0.0011257827863066462
Epoch 497: Loss = 0.0011257697531823624
Epoch 498: Loss = 0.001125756979417252
Epoch 499: Loss = 0.0011257444598500672
Epoch 500: Loss = 0.0011257321894222695
Epoch 501: Loss = 0.0011257201631759849
Epoch 502: Loss = 0.0011257083762520013
Epoch 503: Loss = 0.001125696823887805
Epoch 504: Loss = 0.0011256855014156561
Epoch 505: Loss = 0.0011256744042607032
Epoch 506: Loss = 0.0011256635279391339
Epoch 507: Loss = 0.0011256528680563635
Epoch 508: Loss = 0.0011256424203052605
Epoch 509: Loss = 0.0011256321804644044
Epoch 510: Loss = 0.0011256221443963813
Epoch 511: Loss = 0.0011256123080461118
Epoch 512: Loss = 0.0011256026674392127
Epoch 513: Loss = 0.0011255932186803909
Epoch 514: Loss = 0.0011255839579518696
Epoch 515: Loss = 0.001125574881511846
Epoch 516: Loss = 0.0011255659856929789
Epoc

Epoch 708: Loss = 0.0011251370921621792
Epoch 709: Loss = 0.0011251369083513704
Epoch 710: Loss = 0.0011251367281983967
Epoch 711: Loss = 0.001125136551630467
Epoch 712: Loss = 0.0011251363785762393
Epoch 713: Loss = 0.0011251362089657907
Epoch 714: Loss = 0.00112513604273059
Epoch 715: Loss = 0.0011251358798034699
Epoch 716: Loss = 0.0011251357201185993
Epoch 717: Loss = 0.0011251355636114576
Epoch 718: Loss = 0.0011251354102188083
Epoch 719: Loss = 0.0011251352598786726
Epoch 720: Loss = 0.0011251351125303054
Epoch 721: Loss = 0.001125134968114171
Epoch 722: Loss = 0.0011251348265719175
Epoch 723: Loss = 0.0011251346878463548
Epoch 724: Loss = 0.001125134551881431
Epoch 725: Loss = 0.001125134418622209
Epoch 726: Loss = 0.0011251342880148456
Epoch 727: Loss = 0.0011251341600065688
Epoch 728: Loss = 0.0011251340345456566
Epoch 729: Loss = 0.0011251339115814166
Epoch 730: Loss = 0.0011251337910641649
Epoch 731: Loss = 0.0011251336729452067
Epoch 732: Loss = 0.0011251335571768155
Epoch 

Epoch 919: Loss = 0.0011251279883519227
Epoch 920: Loss = 0.001125127985706938
Epoch 921: Loss = 0.0011251279831145885
Epoch 922: Loss = 0.0011251279805738266
Epoch 923: Loss = 0.001125127978083626
Epoch 924: Loss = 0.0011251279756429803
Epoch 925: Loss = 0.0011251279732509038
Epoch 926: Loss = 0.0011251279709064293
Epoch 927: Loss = 0.0011251279686086098
Epoch 928: Loss = 0.001125127966356517
Epoch 929: Loss = 0.001125127964149241
Epoch 930: Loss = 0.0011251279619858895
Epoch 931: Loss = 0.001125127959865589
Epoch 932: Loss = 0.0011251279577874822
Epoch 933: Loss = 0.00112512795575073
Epoch 934: Loss = 0.0011251279537545088
Epoch 935: Loss = 0.0011251279517980127
Epoch 936: Loss = 0.0011251279498804508
Epoch 937: Loss = 0.0011251279480010484
Epoch 938: Loss = 0.0011251279461590461
Epoch 939: Loss = 0.0011251279443536997
Epoch 940: Loss = 0.0011251279425842796
Epoch 941: Loss = 0.0011251279408500709
Epoch 942: Loss = 0.001125127939150373
Epoch 943: Loss = 0.0011251279374844992
Epoch 94