In [5]:
import numpy as np
import pandas as pd

patientdata = []
for filenum in range(1, 71):
    patientnum = 'Patient Number ' + str(filenum)
    if filenum < 10:
        with open("C:\\Users\\Ayman\\Documents\\machinelearning\\hw5\\diabetes-data\\Diabetes-Data\\data-0"+str(filenum), "r") as file:
            for line in file:
                fourth = str(line)
                date = fourth[0:fourth.index('\t')]
                fourth = fourth.replace(date, '')
                fourth = fourth.replace('\t', '', 1)
                time = fourth[0:fourth.index('\t')]
                fourth = fourth.replace(time, '')
                fourth = fourth.replace('\t', '', 1)
                third = fourth[0:fourth.index('\t')]
                patientdata.append(float(third))
    else:
        with open("C:\\Users\\Ayman\\Documents\\machinelearning\\hw5\\diabetes-data\\Diabetes-Data\\data-"+str(filenum), "r") as file:
            for line in file:
                fourth = str(line)
                date = fourth[0:fourth.index('\t')]
                fourth = fourth.replace(date, '')
                fourth = fourth.replace('\t', '', 1)
                time = fourth[0:fourth.index('\t')]
                fourth = fourth.replace(time, '')
                fourth = fourth.replace('\t', '', 1)
                third = fourth[0:fourth.index('\t')]
                patientdata.append(float(third))

df = pd.DataFrame(patientdata, columns=['col3'])#one hot encoding for the dataframe
onehotencoded = pd.get_dummies(df['col3'], prefix='col3')
datahot = pd.concat([df, onehotencoded], axis=1)

#df_encoded.to_csv("C:\\Users\\Ayman\\Documents\\machinelearning\\hw4\\test_encoded.csv", index=False)
#print(df_encoded)

In [6]:
datahot = datahot.astype(int)#convering the booleans to int for 0 and 1
print(datahot.values)

[[58  0  0 ...  0  0  0]
 [33  0  0 ...  0  0  0]
 [34  0  0 ...  0  0  0]
 ...
 [34  0  0 ...  0  0  0]
 [34  0  0 ...  0  0  0]
 [34  0  0 ...  0  0  0]]


In [7]:
n = 5
def generatengrams(data, n):
    ngrams_list = [tuple(data[i:i+n]) for i in range(len(data)-n+1)]
    return ngrams_list

ngrams = generatengrams(patientdata, n)#generating ngrams and placing those ngrams into the dataframe

ngramsdf = pd.DataFrame(ngrams, columns=[f'Ngram_{i+1}' for i in range(n)])

print(ngramsdf)

       Ngram_1  Ngram_2  Ngram_3  Ngram_4  Ngram_5
0         58.0     33.0     34.0     62.0     33.0
1         33.0     34.0     62.0     33.0     48.0
2         34.0     62.0     33.0     48.0     58.0
3         62.0     33.0     48.0     58.0     33.0
4         33.0     48.0     58.0     33.0     34.0
...        ...      ...      ...      ...      ...
29321     33.0     34.0     48.0     58.0     33.0
29322     34.0     48.0     58.0     33.0     34.0
29323     48.0     58.0     33.0     34.0     34.0
29324     58.0     33.0     34.0     34.0     34.0
29325     33.0     34.0     34.0     34.0     34.0

[29326 rows x 5 columns]


In [8]:
def hashing(patientdata, n):
    hashed = np.zeros(n)
    for x in patientdata:
        i = hash(str(x)) % n
        hashed[i] += 1
    return hashed
hasheddata = hashing(patientdata, 100)
print(hasheddata)

[0.000e+00 0.000e+00 3.518e+03 0.000e+00 0.000e+00 1.000e+00 0.000e+00
 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 1.053e+03 0.000e+00
 0.000e+00 0.000e+00 0.000e+00 2.190e+02 2.000e+01 0.000e+00 0.000e+00
 0.000e+00 0.000e+00 0.000e+00 0.000e+00 1.390e+02 0.000e+00 0.000e+00
 3.310e+02 0.000e+00 3.830e+03 0.000e+00 3.400e+01 0.000e+00 0.000e+00
 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 2.209e+03
 0.000e+00 0.000e+00 0.000e+00 3.300e+01 0.000e+00 9.800e+01 0.000e+00
 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 6.800e+01
 0.000e+00 0.000e+00 0.000e+00 0.000e+00 1.600e+02 0.000e+00 0.000e+00
 0.000e+00 0.000e+00 2.771e+03 0.000e+00 1.190e+02 0.000e+00 0.000e+00
 0.000e+00 0.000e+00 0.000e+00 9.518e+03 1.000e+00 3.160e+03 0.000e+00
 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 1.894e+03
 0.000e+00 1.540e+02 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
 0.000

In [25]:
from sklearn.model_selection import train_test_split

xtrain, xtest, ytrain, ytest = train_test_split(datahot.drop(columns=['col3']), datahot['col3'], test_size=0.2, random_state=42)

In [29]:
from sklearn.model_selection import train_test_split

xtrain, xtest, ytrain, ytest = train_test_split(datahot.drop(columns=['col3']), datahot['col3'], test_size=0.2, random_state=42)

def ginimpurity(labels):
    counts = np.unique(labels, return_counts=True)[1]
    probabilities = counts / len(labels)#gini impurity calculation
    gini = 1 - np.sum(probabilities**2)
    return gini


def informationgain(groups, y):
    total = sum(len(group) for group in groups)
    ig = ginimpurity(y)#uses impurity to calculate the id
    for group in groups:
        proportion = len(group) / total
        ig -= proportion * ginimpurity(group)
    return ig

def split(X, y, feature_index, threshold):
    left_X, left_y, right_X, right_y = [], [], [], []
    for i, val in enumerate(X[:, feature_index]):
        if val <= threshold:#splitting it based on features
            left_X.append(X[i])
            left_y.append(y[i])
        else:
            right_X.append(X[i])
            right_y.append(y[i])
    return np.array(left_X), np.array(left_y), np.array(right_X), np.array(right_y)


def bestsplit(X, y):
    best_feature_index, best_threshold, best_info_gain = None, None, 0
    for feature_index in range(X.shape[1]):
        thresholds = np.unique(X[:, feature_index])
        for threshold in thresholds:
            groups = split(X, y, feature_index, threshold)
            info_gain = informationgain([groups[1], groups[3]], y)#takes it and compares and selects the best one
            if info_gain > best_info_gain:
                best_feature_index, best_threshold, best_info_gain = feature_index, threshold, info_gain
    return best_feature_index, best_threshold, best_info_gain





def build_tree(X, y, max_depth, depth):
    print(f"Depth {depth}, Number of instances: {len(X)}, Classes: {np.unique(y)}")
    if depth == max_depth or len(np.unique(y)) == 1:
        return Node(value=np.bincount(y).argmax())
    
    best_feature_index, best_threshold, best_info_gain = bestsplit(X, y)
    if best_info_gain == 0:
        return Node(value=np.bincount(y).argmax())
    
    left_X, left_y, right_X, right_y = split(X, y, best_feature_index, best_threshold)
    left_subtree = build_tree(left_X, left_y, max_depth, depth + 1)
    right_subtree = build_tree(right_X, right_y, max_depth, depth + 1)
    
    return Node(best_feature_index, best_threshold, left_subtree, right_subtree)

def predict(node, X):
    if node.value is not None:
        return node.value
    if X[node.feature_index] <= node.threshold:
        return predict(node.left, X)
    else:
        return predict(node.right, X)


decision_tree = build_tree(xtrain.values, ytrain.values, 5, 0)
predictions = []
for i in range(len(xtest)):
    predictions.append(predict(decision_tree, xtest.iloc[i]))
accuracy = sum(predictions == ytest.values) / len(ytest)
print("Decision Tree Accuracy:", accuracy)


################################################################
def random_forest(X_train, y_train, n_estimators, max_depth):
    forest = []
    for _ in range(n_estimators):
        sample_indices = np.random.choice(len(X_train), size=len(X_train), replace=True)
        X_sampled = X_train[sample_indices]
        y_sampled = y_train[sample_indices]
        tree = build_tree(X_sampled, y_sampled, max_depth, 0)
        forest.append(tree)
    return forest
forest = random_forest(xtrain.values, ytrain.values, 5, 5)

#make predictions using random forest
def predict_random_forest(forest, X_test):
    predictions = []
    for i in range(len(X_test)):
        instance_predictions = [predict(tree, X_test.iloc[i]) for tree in forest]
        majority_vote = np.bincount(instance_predictions).argmax()
        predictions.append(majority_vote)
    return predictions

predictionsrf = predict_random_forest(forest, xtest)
accuracy = sum(predictionsrf == ytest.values) / len(ytest)
print("Random Forest Accuracy:", accuracy)


Depth 0, Number of instances: 23464, Classes: [ 0 33 34 35 48 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72]
Depth 1, Number of instances: 15847, Classes: [ 0 34 35 48 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72]
Depth 2, Number of instances: 12782, Classes: [ 0 35 48 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72]
Depth 3, Number of instances: 9981, Classes: [ 0 35 48 56 57 59 60 61 62 63 64 65 66 67 68 69 70 71 72]
Depth 4, Number of instances: 7452, Classes: [ 0 35 48 56 57 59 60 61 63 64 65 66 67 68 69 70 71 72]
Depth 5, Number of instances: 5221, Classes: [ 0 35 48 56 57 59 61 63 64 65 66 67 68 69 70 71 72]
Depth 5, Number of instances: 2231, Classes: [60]
Depth 4, Number of instances: 2529, Classes: [62]
Depth 3, Number of instances: 2801, Classes: [58]
Depth 2, Number of instances: 3065, Classes: [34]
Depth 1, Number of instances: 7617, Classes: [33]
Decision Tree Accuracy: 0.8416297306512104
Depth 0, Number of instances: 23464, Classes: [ 0 33 34 35 48 56 57 58 